2025-05-06 00:02:01,338 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-06 00:02:01,339 [INFO] [33mPress CTRL+C to quit[0m
2025-05-06 00:02:01,340 [INFO]  * Restarting with stat
2025-05-06 00:02:01,638 [WARNING]  * Debugger is active!
2025-05-06 00:02:01,646 [INFO]  * Debugger PIN: 144-915-329
2025-05-06 00:02:04,007 [INFO] 127.0.0.1 - - [06/May/2025 00:02:04] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-06 00:02:04,020 [INFO] 127.0.0.1 - - [06/May/2025 00:02:04] "GET /login HTTP/1.1" 200 -
2025-05-06 00:02:04,075 [INFO] 127.0.0.1 - - [06/May/2025 00:02:04] "GET /static/style.css HTTP/1.1" 200 -
2025-05-06 00:02:06,080 [INFO] 127.0.0.1 - - [06/May/2025 00:02:06] "GET /signup HTTP/1.1" 200 -
2025-05-06 00:02:06,100 [INFO] 127.0.0.1 - - [06/May/2025 00:02:06] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2025-05-06 00:02:20,162 [INFO] 127.0.0.1 - - [06/May/2025 00:02:20] "[32mPOST /signup HTTP/1.1[0m" 302 -
2025-05-06 00:02:20,193 [INFO] 127.0.0.1 - - [06/May/2025 00:02:20] "GET /setup-2fa HTTP/1.1" 200 -
2025-05-06 00:02:20,216 [INFO] 127.0.0.1 - - [06/May/2025 00:02:20] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2025-05-06 00:02:31,651 [INFO] 127.0.0.1 - - [06/May/2025 00:02:31] "[32mGET /setup-2fa HTTP/1.1[0m" 302 -
2025-05-06 00:02:31,670 [INFO] 127.0.0.1 - - [06/May/2025 00:02:31] "GET /login HTTP/1.1" 200 -
2025-05-06 00:02:31,694 [INFO] 127.0.0.1 - - [06/May/2025 00:02:31] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2025-05-06 00:02:37,474 [INFO] 127.0.0.1 - - [06/May/2025 00:02:37] "GET /signup HTTP/1.1" 200 -
2025-05-06 00:02:37,499 [INFO] 127.0.0.1 - - [06/May/2025 00:02:37] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2025-05-06 00:03:01,468 [INFO] 127.0.0.1 - - [06/May/2025 00:03:01] "[32mPOST /signup HTTP/1.1[0m" 302 -
2025-05-06 00:03:01,487 [INFO] 127.0.0.1 - - [06/May/2025 00:03:01] "GET /setup-2fa HTTP/1.1" 200 -
2025-05-06 00:03:01,510 [INFO] 127.0.0.1 - - [06/May/2025 00:03:01] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2025-05-06 00:03:40,470 [INFO] 127.0.0.1 - - [06/May/2025 00:03:40] "[32mGET /setup-2fa HTTP/1.1[0m" 302 -
2025-05-06 00:03:40,480 [INFO] 127.0.0.1 - - [06/May/2025 00:03:40] "GET /login HTTP/1.1" 200 -
2025-05-06 00:03:40,514 [INFO] 127.0.0.1 - - [06/May/2025 00:03:40] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2025-05-06 00:03:43,772 [INFO] 127.0.0.1 - - [06/May/2025 00:03:43] "GET /signup HTTP/1.1" 200 -
2025-05-06 00:03:43,802 [INFO] 127.0.0.1 - - [06/May/2025 00:03:43] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2025-05-06 00:04:07,466 [INFO] 127.0.0.1 - - [06/May/2025 00:04:07] "[32mPOST /signup HTTP/1.1[0m" 302 -
2025-05-06 00:04:07,484 [INFO] 127.0.0.1 - - [06/May/2025 00:04:07] "GET /setup-2fa HTTP/1.1" 200 -
2025-05-06 00:04:07,505 [INFO] 127.0.0.1 - - [06/May/2025 00:04:07] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2025-05-06 00:04:31,742 [INFO] 127.0.0.1 - - [06/May/2025 00:04:31] "[32mGET /setup-2fa HTTP/1.1[0m" 302 -
2025-05-06 00:04:31,761 [INFO] 127.0.0.1 - - [06/May/2025 00:04:31] "GET /login HTTP/1.1" 200 -
2025-05-06 00:04:31,787 [INFO] 127.0.0.1 - - [06/May/2025 00:04:31] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2025-05-06 00:04:33,376 [INFO] 127.0.0.1 - - [06/May/2025 00:04:33] "GET /signup HTTP/1.1" 200 -
2025-05-06 00:04:33,404 [INFO] 127.0.0.1 - - [06/May/2025 00:04:33] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2025-05-06 00:04:53,383 [INFO] 127.0.0.1 - - [06/May/2025 00:04:53] "[32mPOST /signup HTTP/1.1[0m" 302 -
2025-05-06 00:04:53,389 [INFO] 127.0.0.1 - - [06/May/2025 00:04:53] "GET /signup HTTP/1.1" 200 -
2025-05-06 00:04:53,409 [INFO] 127.0.0.1 - - [06/May/2025 00:04:53] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2025-05-06 00:05:16,701 [INFO] 127.0.0.1 - - [06/May/2025 00:05:16] "[32mPOST /signup HTTP/1.1[0m" 302 -
2025-05-06 00:05:16,719 [INFO] 127.0.0.1 - - [06/May/2025 00:05:16] "GET /setup-2fa HTTP/1.1" 200 -
2025-05-06 00:05:16,744 [INFO] 127.0.0.1 - - [06/May/2025 00:05:16] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
2025-05-07 16:39:50,972 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-07 16:39:50,972 [INFO] [33mPress CTRL+C to quit[0m
2025-05-07 16:39:50,973 [INFO]  * Restarting with stat
2025-05-07 16:39:51,409 [WARNING]  * Debugger is active!
2025-05-07 16:39:51,443 [INFO]  * Debugger PIN: 126-490-092
2025-05-07 16:39:58,246 [INFO] 127.0.0.1 - - [07/May/2025 16:39:58] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-07 16:39:58,264 [INFO] 127.0.0.1 - - [07/May/2025 16:39:58] "[32mGET /dashboard HTTP/1.1[0m" 302 -
2025-05-07 16:39:58,289 [INFO] 127.0.0.1 - - [07/May/2025 16:39:58] "GET /login?next=/dashboard HTTP/1.1" 200 -
2025-05-07 16:39:58,337 [INFO] 127.0.0.1 - - [07/May/2025 16:39:58] "[33mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 404 -
2025-05-07 16:40:03,015 [INFO] 127.0.0.1 - - [07/May/2025 16:40:03] "[32mGET /dashboard HTTP/1.1[0m" 302 -
2025-05-07 16:40:03,022 [INFO] 127.0.0.1 - - [07/May/2025 16:40:03] "GET /login?next=/dashboard HTTP/1.1" 200 -
2025-05-07 16:40:03,037 [INFO] 127.0.0.1 - - [07/May/2025 16:40:03] "[33mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 404 -
2025-05-07 16:40:04,051 [INFO] 127.0.0.1 - - [07/May/2025 16:40:04] "[32mGET /upload HTTP/1.1[0m" 302 -
2025-05-07 16:40:04,057 [INFO] 127.0.0.1 - - [07/May/2025 16:40:04] "GET /login?next=/upload HTTP/1.1" 200 -
2025-05-07 16:40:04,071 [INFO] 127.0.0.1 - - [07/May/2025 16:40:04] "[33mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 404 -
2025-05-07 16:40:04,586 [INFO] 127.0.0.1 - - [07/May/2025 16:40:04] "[32mGET /dashboard HTTP/1.1[0m" 302 -
2025-05-07 16:40:04,588 [INFO] 127.0.0.1 - - [07/May/2025 16:40:04] "GET /login?next=/dashboard HTTP/1.1" 200 -
2025-05-07 16:40:04,597 [INFO] 127.0.0.1 - - [07/May/2025 16:40:04] "[33mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 404 -
2025-05-07 16:40:04,967 [INFO] 127.0.0.1 - - [07/May/2025 16:40:04] "[32mGET /upload HTTP/1.1[0m" 302 -
2025-05-07 16:40:04,972 [INFO] 127.0.0.1 - - [07/May/2025 16:40:04] "GET /login?next=/upload HTTP/1.1" 200 -
2025-05-07 16:40:04,985 [INFO] 127.0.0.1 - - [07/May/2025 16:40:04] "[33mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 404 -
2025-05-07 16:40:05,368 [INFO] 127.0.0.1 - - [07/May/2025 16:40:05] "[32mGET /dashboard HTTP/1.1[0m" 302 -
2025-05-07 16:40:05,374 [INFO] 127.0.0.1 - - [07/May/2025 16:40:05] "GET /login?next=/dashboard HTTP/1.1" 200 -
2025-05-07 16:40:05,388 [INFO] 127.0.0.1 - - [07/May/2025 16:40:05] "[33mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 404 -
2025-05-07 16:40:05,709 [INFO] 127.0.0.1 - - [07/May/2025 16:40:05] "[32mGET /upload HTTP/1.1[0m" 302 -
2025-05-07 16:40:05,714 [INFO] 127.0.0.1 - - [07/May/2025 16:40:05] "GET /login?next=/upload HTTP/1.1" 200 -
2025-05-07 16:40:05,725 [INFO] 127.0.0.1 - - [07/May/2025 16:40:05] "[33mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 404 -
2025-05-07 16:40:06,171 [INFO] 127.0.0.1 - - [07/May/2025 16:40:06] "[32mGET /share HTTP/1.1[0m" 302 -
2025-05-07 16:40:06,176 [INFO] 127.0.0.1 - - [07/May/2025 16:40:06] "GET /login?next=/share HTTP/1.1" 200 -
2025-05-07 16:40:06,189 [INFO] 127.0.0.1 - - [07/May/2025 16:40:06] "[33mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 404 -
2025-05-07 16:40:06,605 [INFO] 127.0.0.1 - - [07/May/2025 16:40:06] "[32mGET /shared_with_me HTTP/1.1[0m" 302 -
2025-05-07 16:40:06,610 [INFO] 127.0.0.1 - - [07/May/2025 16:40:06] "GET /login?next=/shared_with_me HTTP/1.1" 200 -
2025-05-07 16:40:06,624 [INFO] 127.0.0.1 - - [07/May/2025 16:40:06] "[33mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 404 -
2025-05-07 16:40:07,017 [INFO] 127.0.0.1 - - [07/May/2025 16:40:07] "[32mGET /deadlines HTTP/1.1[0m" 302 -
2025-05-07 16:40:07,021 [INFO] 127.0.0.1 - - [07/May/2025 16:40:07] "GET /login?next=/deadlines HTTP/1.1" 200 -
2025-05-07 16:40:07,037 [INFO] 127.0.0.1 - - [07/May/2025 16:40:07] "[33mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 404 -
2025-05-07 16:48:02,257 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-07 16:48:02,258 [INFO] [33mPress CTRL+C to quit[0m
2025-05-07 16:48:02,259 [INFO]  * Restarting with stat
2025-05-07 16:48:02,678 [WARNING]  * Debugger is active!
2025-05-07 16:48:02,720 [INFO]  * Debugger PIN: 126-490-092
2025-05-07 16:48:11,047 [INFO] 127.0.0.1 - - [07/May/2025 16:48:11] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-07 16:48:11,060 [INFO] 127.0.0.1 - - [07/May/2025 16:48:11] "[32mGET /dashboard HTTP/1.1[0m" 302 -
2025-05-07 16:48:11,091 [INFO] 127.0.0.1 - - [07/May/2025 16:48:11] "GET /login?next=/dashboard HTTP/1.1" 200 -
2025-05-07 16:48:11,466 [INFO] 127.0.0.1 - - [07/May/2025 16:48:11] "GET /static/uploads/StudyUdubLogo.png HTTP/1.1" 200 -
2025-05-07 16:51:47,360 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-07 16:51:47,361 [INFO] [33mPress CTRL+C to quit[0m
2025-05-07 16:51:47,361 [INFO]  * Restarting with stat
2025-05-07 16:51:47,786 [WARNING]  * Debugger is active!
2025-05-07 16:51:47,818 [INFO]  * Debugger PIN: 126-490-092
2025-05-07 16:51:55,002 [INFO] 127.0.0.1 - - [07/May/2025 16:51:55] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-07 16:51:55,019 [INFO] 127.0.0.1 - - [07/May/2025 16:51:55] "[32mGET /dashboard HTTP/1.1[0m" 302 -
2025-05-07 16:51:55,051 [INFO] 127.0.0.1 - - [07/May/2025 16:51:55] "GET /login?next=/dashboard HTTP/1.1" 200 -
2025-05-07 16:51:56,298 [INFO] 127.0.0.1 - - [07/May/2025 16:51:56] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 16:52:01,910 [INFO] 127.0.0.1 - - [07/May/2025 16:52:01] "GET /signup HTTP/1.1" 200 -
2025-05-07 16:52:10,389 [INFO] 127.0.0.1 - - [07/May/2025 16:52:10] "POST /login?next=/dashboard HTTP/1.1" 200 -
2025-05-07 16:52:10,402 [INFO] 127.0.0.1 - - [07/May/2025 16:52:10] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 16:52:11,456 [INFO] 127.0.0.1 - - [07/May/2025 16:52:11] "POST /login?next=/dashboard HTTP/1.1" 200 -
2025-05-07 16:52:11,470 [INFO] 127.0.0.1 - - [07/May/2025 16:52:11] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 16:52:12,195 [INFO] 127.0.0.1 - - [07/May/2025 16:52:12] "POST /login?next=/dashboard HTTP/1.1" 200 -
2025-05-07 16:52:12,207 [INFO] 127.0.0.1 - - [07/May/2025 16:52:12] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 16:52:12,738 [INFO] 127.0.0.1 - - [07/May/2025 16:52:12] "POST /login?next=/dashboard HTTP/1.1" 200 -
2025-05-07 16:52:12,749 [INFO] 127.0.0.1 - - [07/May/2025 16:52:12] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 16:52:13,059 [INFO] 127.0.0.1 - - [07/May/2025 16:52:13] "POST /login?next=/dashboard HTTP/1.1" 200 -
2025-05-07 16:52:13,070 [INFO] 127.0.0.1 - - [07/May/2025 16:52:13] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 16:52:13,814 [INFO] 127.0.0.1 - - [07/May/2025 16:52:13] "POST /login?next=/dashboard HTTP/1.1" 200 -
2025-05-07 16:52:13,830 [INFO] 127.0.0.1 - - [07/May/2025 16:52:13] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 16:52:14,993 [INFO] 127.0.0.1 - - [07/May/2025 16:52:14] "GET /forgot HTTP/1.1" 200 -
2025-05-07 16:52:17,417 [INFO] 127.0.0.1 - - [07/May/2025 16:52:17] "POST /forgot HTTP/1.1" 200 -
2025-05-07 16:54:25,291 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-07 16:54:25,291 [INFO] [33mPress CTRL+C to quit[0m
2025-05-07 16:54:25,291 [INFO]  * Restarting with stat
2025-05-07 16:54:25,713 [WARNING]  * Debugger is active!
2025-05-07 16:54:25,745 [INFO]  * Debugger PIN: 126-490-092
2025-05-07 16:54:33,115 [INFO] 127.0.0.1 - - [07/May/2025 16:54:33] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-07 16:54:33,129 [INFO] 127.0.0.1 - - [07/May/2025 16:54:33] "[32mGET /dashboard HTTP/1.1[0m" 302 -
2025-05-07 16:54:33,159 [INFO] 127.0.0.1 - - [07/May/2025 16:54:33] "GET /login?next=/dashboard HTTP/1.1" 200 -
2025-05-07 16:54:33,176 [INFO] 127.0.0.1 - - [07/May/2025 16:54:33] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 16:54:35,184 [INFO] 127.0.0.1 - - [07/May/2025 16:54:35] "GET /signup HTTP/1.1" 200 -
2025-05-07 16:54:37,691 [INFO] 127.0.0.1 - - [07/May/2025 16:54:37] "GET /signup HTTP/1.1" 200 -
2025-05-07 16:54:39,848 [INFO] 127.0.0.1 - - [07/May/2025 16:54:39] "GET /signup HTTP/1.1" 200 -
2025-05-07 16:54:40,326 [INFO] 127.0.0.1 - - [07/May/2025 16:54:40] "GET /signup HTTP/1.1" 200 -
2025-05-07 16:54:42,979 [INFO] 127.0.0.1 - - [07/May/2025 16:54:42] "GET /login HTTP/1.1" 200 -
2025-05-07 16:54:43,003 [INFO] 127.0.0.1 - - [07/May/2025 16:54:43] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 16:54:44,640 [INFO] 127.0.0.1 - - [07/May/2025 16:54:44] "POST /login HTTP/1.1" 200 -
2025-05-07 16:54:44,650 [INFO] 127.0.0.1 - - [07/May/2025 16:54:44] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 16:54:45,342 [INFO] 127.0.0.1 - - [07/May/2025 16:54:45] "POST /login HTTP/1.1" 200 -
2025-05-07 16:54:45,355 [INFO] 127.0.0.1 - - [07/May/2025 16:54:45] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 16:54:45,574 [INFO] 127.0.0.1 - - [07/May/2025 16:54:45] "POST /login HTTP/1.1" 200 -
2025-05-07 16:54:45,585 [INFO] 127.0.0.1 - - [07/May/2025 16:54:45] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 16:54:45,791 [INFO] 127.0.0.1 - - [07/May/2025 16:54:45] "POST /login HTTP/1.1" 200 -
2025-05-07 16:54:45,802 [INFO] 127.0.0.1 - - [07/May/2025 16:54:45] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 16:54:45,989 [INFO] 127.0.0.1 - - [07/May/2025 16:54:45] "POST /login HTTP/1.1" 200 -
2025-05-07 16:54:45,999 [INFO] 127.0.0.1 - - [07/May/2025 16:54:45] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 16:54:46,207 [INFO] 127.0.0.1 - - [07/May/2025 16:54:46] "POST /login HTTP/1.1" 200 -
2025-05-07 16:54:46,218 [INFO] 127.0.0.1 - - [07/May/2025 16:54:46] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 16:54:46,595 [INFO] 127.0.0.1 - - [07/May/2025 16:54:46] "POST /login HTTP/1.1" 200 -
2025-05-07 16:54:46,608 [INFO] 127.0.0.1 - - [07/May/2025 16:54:46] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 16:54:46,806 [INFO] 127.0.0.1 - - [07/May/2025 16:54:46] "POST /login HTTP/1.1" 200 -
2025-05-07 16:54:46,817 [INFO] 127.0.0.1 - - [07/May/2025 16:54:46] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 16:59:37,587 [INFO] 127.0.0.1 - - [07/May/2025 16:59:37] "GET /login HTTP/1.1" 200 -
2025-05-07 16:59:37,632 [INFO] 127.0.0.1 - - [07/May/2025 16:59:37] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 16:59:38,811 [INFO] 127.0.0.1 - - [07/May/2025 16:59:38] "GET /signup HTTP/1.1" 200 -
2025-05-07 16:59:41,201 [INFO] 127.0.0.1 - - [07/May/2025 16:59:41] "GET /login HTTP/1.1" 200 -
2025-05-07 16:59:41,217 [INFO] 127.0.0.1 - - [07/May/2025 16:59:41] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 17:06:46,635 [INFO]  * Detected change in '/Users/donnapeari/Desktop/agile-projec/StudyUdub-5/app.py', reloading
2025-05-07 17:06:46,739 [INFO]  * Restarting with stat
2025-05-07 17:06:48,116 [WARNING]  * Debugger is active!
2025-05-07 17:06:48,151 [INFO]  * Debugger PIN: 126-490-092
2025-05-07 17:06:56,761 [INFO]  * Detected change in '/Users/donnapeari/Desktop/agile-projec/StudyUdub-5/app.py', reloading
2025-05-07 17:06:56,816 [INFO]  * Restarting with stat
2025-05-07 17:06:57,422 [WARNING]  * Debugger is active!
2025-05-07 17:06:57,445 [INFO]  * Debugger PIN: 126-490-092
2025-05-07 17:08:10,881 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-07 17:08:10,881 [INFO] [33mPress CTRL+C to quit[0m
2025-05-07 17:08:10,882 [INFO]  * Restarting with stat
2025-05-07 17:08:11,316 [WARNING]  * Debugger is active!
2025-05-07 17:08:11,343 [INFO]  * Debugger PIN: 126-490-092
2025-05-07 17:08:19,076 [INFO] 127.0.0.1 - - [07/May/2025 17:08:19] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-07 17:08:19,084 [INFO] 127.0.0.1 - - [07/May/2025 17:08:19] "[32mGET /dashboard HTTP/1.1[0m" 302 -
2025-05-07 17:08:19,124 [INFO] 127.0.0.1 - - [07/May/2025 17:08:19] "GET /login?next=/dashboard HTTP/1.1" 200 -
2025-05-07 17:08:19,197 [INFO] 127.0.0.1 - - [07/May/2025 17:08:19] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 17:08:20,929 [INFO] 127.0.0.1 - - [07/May/2025 17:08:20] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-07 17:08:20,936 [INFO] 127.0.0.1 - - [07/May/2025 17:08:20] "[32mGET /dashboard HTTP/1.1[0m" 302 -
2025-05-07 17:08:20,956 [INFO] 127.0.0.1 - - [07/May/2025 17:08:20] "GET /login?next=/dashboard HTTP/1.1" 200 -
2025-05-07 17:08:21,011 [INFO] 127.0.0.1 - - [07/May/2025 17:08:21] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 17:08:24,418 [INFO] 127.0.0.1 - - [07/May/2025 17:08:24] "GET /login HTTP/1.1" 200 -
2025-05-07 17:08:24,438 [INFO] 127.0.0.1 - - [07/May/2025 17:08:24] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 17:08:25,638 [INFO] 127.0.0.1 - - [07/May/2025 17:08:25] "GET /signup HTTP/1.1" 200 -
2025-05-07 17:08:37,114 [INFO] 127.0.0.1 - - [07/May/2025 17:08:37] "[32mPOST /signup HTTP/1.1[0m" 302 -
2025-05-07 17:08:37,334 [INFO] 127.0.0.1 - - [07/May/2025 17:08:37] "[35m[1mGET /setup-2fa HTTP/1.1[0m" 500 -
2025-05-07 17:08:37,349 [INFO] 127.0.0.1 - - [07/May/2025 17:08:37] "GET /setup-2fa?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
2025-05-07 17:08:37,349 [INFO] 127.0.0.1 - - [07/May/2025 17:08:37] "GET /setup-2fa?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2025-05-07 17:08:37,374 [INFO] 127.0.0.1 - - [07/May/2025 17:08:37] "GET /setup-2fa?__debugger__=yes&cmd=resource&f=console.png&s=NvTxXAgxtMNW4GWWgIVc HTTP/1.1" 200 -
2025-05-07 17:08:37,410 [INFO] 127.0.0.1 - - [07/May/2025 17:08:37] "GET /setup-2fa?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
2025-05-07 17:09:49,025 [INFO] 127.0.0.1 - - [07/May/2025 17:09:49] "GET /signup HTTP/1.1" 200 -
2025-05-07 17:10:05,240 [INFO] 127.0.0.1 - - [07/May/2025 17:10:05] "GET /signup HTTP/1.1" 200 -
2025-05-07 17:10:13,241 [INFO] 127.0.0.1 - - [07/May/2025 17:10:13] "[32mPOST /signup HTTP/1.1[0m" 302 -
2025-05-07 17:10:13,246 [INFO] 127.0.0.1 - - [07/May/2025 17:10:13] "GET /signup HTTP/1.1" 200 -
2025-05-07 17:10:26,094 [INFO] 127.0.0.1 - - [07/May/2025 17:10:26] "[32mPOST /signup HTTP/1.1[0m" 302 -
2025-05-07 17:10:26,100 [INFO] 127.0.0.1 - - [07/May/2025 17:10:26] "GET /signup HTTP/1.1" 200 -
2025-05-07 17:10:28,306 [INFO] 127.0.0.1 - - [07/May/2025 17:10:28] "[32mGET /logout HTTP/1.1[0m" 302 -
2025-05-07 17:10:28,310 [INFO] 127.0.0.1 - - [07/May/2025 17:10:28] "GET /login HTTP/1.1" 200 -
2025-05-07 17:10:28,325 [INFO] 127.0.0.1 - - [07/May/2025 17:10:28] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 17:10:29,916 [INFO] 127.0.0.1 - - [07/May/2025 17:10:29] "GET /login HTTP/1.1" 200 -
2025-05-07 17:10:29,926 [INFO] 127.0.0.1 - - [07/May/2025 17:10:29] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 17:10:30,510 [INFO] 127.0.0.1 - - [07/May/2025 17:10:30] "GET /login HTTP/1.1" 200 -
2025-05-07 17:10:30,526 [INFO] 127.0.0.1 - - [07/May/2025 17:10:30] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 17:10:30,997 [INFO] 127.0.0.1 - - [07/May/2025 17:10:30] "GET /login HTTP/1.1" 200 -
2025-05-07 17:10:31,010 [INFO] 127.0.0.1 - - [07/May/2025 17:10:31] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 17:10:31,510 [INFO] 127.0.0.1 - - [07/May/2025 17:10:31] "GET /login HTTP/1.1" 200 -
2025-05-07 17:10:31,535 [INFO] 127.0.0.1 - - [07/May/2025 17:10:31] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 17:10:32,726 [INFO] 127.0.0.1 - - [07/May/2025 17:10:32] "GET /signup HTTP/1.1" 200 -
2025-05-07 17:14:21,398 [INFO] 127.0.0.1 - - [07/May/2025 17:14:21] "GET /signup HTTP/1.1" 200 -
2025-05-07 17:14:38,586 [INFO] 127.0.0.1 - - [07/May/2025 17:14:38] "GET /signup HTTP/1.1" 200 -
2025-05-07 17:14:48,863 [INFO] 127.0.0.1 - - [07/May/2025 17:14:48] "GET /login HTTP/1.1" 200 -
2025-05-07 17:14:48,886 [INFO] 127.0.0.1 - - [07/May/2025 17:14:48] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 17:20:37,882 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-07 17:20:37,882 [INFO] [33mPress CTRL+C to quit[0m
2025-05-07 17:20:37,883 [INFO]  * Restarting with stat
2025-05-07 17:20:38,306 [WARNING]  * Debugger is active!
2025-05-07 17:20:38,339 [INFO]  * Debugger PIN: 126-490-092
2025-05-07 17:20:45,427 [INFO] 127.0.0.1 - - [07/May/2025 17:20:45] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-07 17:20:45,456 [INFO] 127.0.0.1 - - [07/May/2025 17:20:45] "[32mGET /dashboard HTTP/1.1[0m" 302 -
2025-05-07 17:20:45,489 [INFO] 127.0.0.1 - - [07/May/2025 17:20:45] "GET /login?next=/dashboard HTTP/1.1" 200 -
2025-05-07 17:20:45,558 [INFO] 127.0.0.1 - - [07/May/2025 17:20:45] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 17:20:49,322 [INFO] 127.0.0.1 - - [07/May/2025 17:20:49] "GET /signup HTTP/1.1" 200 -
2025-05-07 17:20:49,343 [INFO] 127.0.0.1 - - [07/May/2025 17:20:49] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 17:20:52,296 [INFO] 127.0.0.1 - - [07/May/2025 17:20:52] "GET /login HTTP/1.1" 200 -
2025-05-07 17:20:52,311 [INFO] 127.0.0.1 - - [07/May/2025 17:20:52] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 17:20:53,687 [INFO] 127.0.0.1 - - [07/May/2025 17:20:53] "GET /signup HTTP/1.1" 200 -
2025-05-07 17:20:53,708 [INFO] 127.0.0.1 - - [07/May/2025 17:20:53] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 17:21:02,578 [INFO] 127.0.0.1 - - [07/May/2025 17:21:02] "[32mPOST /signup HTTP/1.1[0m" 302 -
2025-05-07 17:21:02,580 [INFO] 127.0.0.1 - - [07/May/2025 17:21:02] "GET /signup HTTP/1.1" 200 -
2025-05-07 17:21:02,591 [INFO] 127.0.0.1 - - [07/May/2025 17:21:02] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 17:21:05,988 [INFO] 127.0.0.1 - - [07/May/2025 17:21:05] "GET /login HTTP/1.1" 200 -
2025-05-07 17:21:06,010 [INFO] 127.0.0.1 - - [07/May/2025 17:21:06] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 17:21:06,868 [INFO] 127.0.0.1 - - [07/May/2025 17:21:06] "GET /login HTTP/1.1" 200 -
2025-05-07 17:21:06,887 [INFO] 127.0.0.1 - - [07/May/2025 17:21:06] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-07 17:21:07,798 [INFO] 127.0.0.1 - - [07/May/2025 17:21:07] "GET /signup HTTP/1.1" 200 -
2025-05-07 17:21:07,810 [INFO] 127.0.0.1 - - [07/May/2025 17:21:07] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 14:27:27,671 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-08 14:27:27,672 [INFO] [33mPress CTRL+C to quit[0m
2025-05-08 14:27:36,074 [INFO] 127.0.0.1 - - [08/May/2025 14:27:36] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-08 14:27:36,253 [INFO] 127.0.0.1 - - [08/May/2025 14:27:36] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-08 14:27:36,265 [INFO] 127.0.0.1 - - [08/May/2025 14:27:36] "[32mGET /dashboard HTTP/1.1[0m" 302 -
2025-05-08 14:27:36,297 [INFO] 127.0.0.1 - - [08/May/2025 14:27:36] "GET /login?next=/dashboard HTTP/1.1" 200 -
2025-05-08 14:27:36,473 [INFO] 127.0.0.1 - - [08/May/2025 14:27:36] "GET /static/uploads/StudyUdubLogo.png HTTP/1.1" 200 -
2025-05-08 14:27:39,372 [INFO] 127.0.0.1 - - [08/May/2025 14:27:39] "GET /signup HTTP/1.1" 200 -
2025-05-08 14:27:39,387 [INFO] 127.0.0.1 - - [08/May/2025 14:27:39] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 14:27:46,881 [INFO] 127.0.0.1 - - [08/May/2025 14:27:46] "GET /login HTTP/1.1" 200 -
2025-05-08 14:27:46,898 [INFO] 127.0.0.1 - - [08/May/2025 14:27:46] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 14:27:48,857 [INFO] 127.0.0.1 - - [08/May/2025 14:27:48] "GET /forgot HTTP/1.1" 200 -
2025-05-08 14:27:51,698 [INFO] 127.0.0.1 - - [08/May/2025 14:27:51] "GET /login HTTP/1.1" 200 -
2025-05-08 14:27:51,712 [INFO] 127.0.0.1 - - [08/May/2025 14:27:51] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 14:27:53,773 [INFO] 127.0.0.1 - - [08/May/2025 14:27:53] "GET /forgot HTTP/1.1" 200 -
2025-05-08 17:35:30,171 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-08 17:35:30,172 [INFO] [33mPress CTRL+C to quit[0m
2025-05-08 17:35:36,385 [INFO] 127.0.0.1 - - [08/May/2025 17:35:36] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-08 17:35:36,512 [INFO] 127.0.0.1 - - [08/May/2025 17:35:36] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 17:35:36,513 [INFO] 127.0.0.1 - - [08/May/2025 17:35:36] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-08 17:35:36,516 [INFO] 127.0.0.1 - - [08/May/2025 17:35:36] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 17:35:36,806 [INFO] 127.0.0.1 - - [08/May/2025 17:35:36] "GET /static/uploads/StudyUdubLogo.png HTTP/1.1" 200 -
2025-05-08 17:35:38,133 [ERROR] Exception on /grades [GET]
Traceback (most recent call last):
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 74, in wrapped_view
    return view(**kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 305, in grades_view
    return render_template('grades.html', grades=session.get('grades', []), courses=session.get('courses', []))
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/base.html", line 173, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 58, in block 'content'
    {% for unit, summary in summaries.items() %}
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'summaries' is undefined
2025-05-08 17:35:38,139 [INFO] 127.0.0.1 - - [08/May/2025 17:35:38] "[35m[1mGET /grades HTTP/1.1[0m" 500 -
2025-05-08 17:35:41,238 [INFO] 127.0.0.1 - - [08/May/2025 17:35:41] "GET /deadlines HTTP/1.1" 200 -
2025-05-08 17:35:41,252 [INFO] 127.0.0.1 - - [08/May/2025 17:35:41] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:35:41,907 [INFO] 127.0.0.1 - - [08/May/2025 17:35:41] "GET /shared_with_me HTTP/1.1" 200 -
2025-05-08 17:35:41,921 [INFO] 127.0.0.1 - - [08/May/2025 17:35:41] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:35:42,396 [INFO] 127.0.0.1 - - [08/May/2025 17:35:42] "GET /share HTTP/1.1" 200 -
2025-05-08 17:35:42,409 [INFO] 127.0.0.1 - - [08/May/2025 17:35:42] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:35:42,798 [INFO] 127.0.0.1 - - [08/May/2025 17:35:42] "GET /upload HTTP/1.1" 200 -
2025-05-08 17:35:42,813 [INFO] 127.0.0.1 - - [08/May/2025 17:35:42] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:35:43,393 [INFO] 127.0.0.1 - - [08/May/2025 17:35:43] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 17:35:43,407 [INFO] 127.0.0.1 - - [08/May/2025 17:35:43] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:35:44,057 [ERROR] Exception on /grades [GET]
Traceback (most recent call last):
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 74, in wrapped_view
    return view(**kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 305, in grades_view
    return render_template('grades.html', grades=session.get('grades', []), courses=session.get('courses', []))
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/base.html", line 173, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 58, in block 'content'
    {% for unit, summary in summaries.items() %}
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'summaries' is undefined
2025-05-08 17:35:44,059 [INFO] 127.0.0.1 - - [08/May/2025 17:35:44] "[35m[1mGET /grades HTTP/1.1[0m" 500 -
2025-05-08 17:35:48,423 [INFO] 127.0.0.1 - - [08/May/2025 17:35:48] "GET /upload HTTP/1.1" 200 -
2025-05-08 17:35:48,438 [INFO] 127.0.0.1 - - [08/May/2025 17:35:48] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:35:48,927 [INFO] 127.0.0.1 - - [08/May/2025 17:35:48] "GET /share HTTP/1.1" 200 -
2025-05-08 17:35:48,942 [INFO] 127.0.0.1 - - [08/May/2025 17:35:48] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:35:50,083 [INFO] 127.0.0.1 - - [08/May/2025 17:35:50] "GET /shared_with_me HTTP/1.1" 200 -
2025-05-08 17:35:50,096 [INFO] 127.0.0.1 - - [08/May/2025 17:35:50] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:35:50,652 [INFO] 127.0.0.1 - - [08/May/2025 17:35:50] "GET /deadlines HTTP/1.1" 200 -
2025-05-08 17:35:50,667 [INFO] 127.0.0.1 - - [08/May/2025 17:35:50] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:35:51,261 [ERROR] Exception on /grades [GET]
Traceback (most recent call last):
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 74, in wrapped_view
    return view(**kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 305, in grades_view
    return render_template('grades.html', grades=session.get('grades', []), courses=session.get('courses', []))
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/base.html", line 173, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 58, in block 'content'
    {% for unit, summary in summaries.items() %}
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'summaries' is undefined
2025-05-08 17:35:51,262 [INFO] 127.0.0.1 - - [08/May/2025 17:35:51] "[35m[1mGET /grades HTTP/1.1[0m" 500 -
2025-05-08 17:35:53,133 [INFO] 127.0.0.1 - - [08/May/2025 17:35:53] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 17:35:53,150 [INFO] 127.0.0.1 - - [08/May/2025 17:35:53] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:35:53,784 [INFO] 127.0.0.1 - - [08/May/2025 17:35:53] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 17:35:53,796 [INFO] 127.0.0.1 - - [08/May/2025 17:35:53] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:35:54,316 [INFO] 127.0.0.1 - - [08/May/2025 17:35:54] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 17:35:54,332 [INFO] 127.0.0.1 - - [08/May/2025 17:35:54] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:35:54,925 [INFO] 127.0.0.1 - - [08/May/2025 17:35:54] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 17:35:54,942 [INFO] 127.0.0.1 - - [08/May/2025 17:35:54] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:35:56,121 [INFO] 127.0.0.1 - - [08/May/2025 17:35:56] "[32mGET /logout HTTP/1.1[0m" 302 -
2025-05-08 17:35:56,133 [INFO] 127.0.0.1 - - [08/May/2025 17:35:56] "GET /login HTTP/1.1" 200 -
2025-05-08 17:35:56,151 [INFO] 127.0.0.1 - - [08/May/2025 17:35:56] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:35:58,100 [INFO] 127.0.0.1 - - [08/May/2025 17:35:58] "POST /login HTTP/1.1" 200 -
2025-05-08 17:35:58,117 [INFO] 127.0.0.1 - - [08/May/2025 17:35:58] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:36:06,298 [INFO] 127.0.0.1 - - [08/May/2025 17:36:06] "GET /forgot HTTP/1.1" 200 -
2025-05-08 17:36:15,327 [INFO] 127.0.0.1 - - [08/May/2025 17:36:15] "POST /forgot HTTP/1.1" 200 -
2025-05-08 17:36:19,055 [INFO] 127.0.0.1 - - [08/May/2025 17:36:19] "GET /login HTTP/1.1" 200 -
2025-05-08 17:36:19,073 [INFO] 127.0.0.1 - - [08/May/2025 17:36:19] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:36:24,110 [INFO] 127.0.0.1 - - [08/May/2025 17:36:24] "GET /reset/ImRvbm5hcGVhcmkyNUBnbWFpbC5jb20i.aBx7CA.nb4cTObw3HV5QiNGYS6IMLeszIM HTTP/1.1" 200 -
2025-05-08 17:36:33,172 [INFO] 127.0.0.1 - - [08/May/2025 17:36:33] "[32mPOST /reset/ImRvbm5hcGVhcmkyNUBnbWFpbC5jb20i.aBx7CA.nb4cTObw3HV5QiNGYS6IMLeszIM HTTP/1.1[0m" 302 -
2025-05-08 17:36:33,175 [INFO] 127.0.0.1 - - [08/May/2025 17:36:33] "GET /login HTTP/1.1" 200 -
2025-05-08 17:36:33,191 [INFO] 127.0.0.1 - - [08/May/2025 17:36:33] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:36:34,717 [INFO] 127.0.0.1 - - [08/May/2025 17:36:34] "[32mPOST /login HTTP/1.1[0m" 302 -
2025-05-08 17:36:34,722 [INFO] 127.0.0.1 - - [08/May/2025 17:36:34] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 17:36:34,733 [INFO] 127.0.0.1 - - [08/May/2025 17:36:34] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:36:36,271 [ERROR] Exception on /grades [GET]
Traceback (most recent call last):
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 74, in wrapped_view
    return view(**kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 305, in grades_view
    return render_template('grades.html', grades=session.get('grades', []), courses=session.get('courses', []))
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/base.html", line 173, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 58, in block 'content'
    {% for unit, summary in summaries.items() %}
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'summaries' is undefined
2025-05-08 17:36:36,272 [INFO] 127.0.0.1 - - [08/May/2025 17:36:36] "[35m[1mGET /grades HTTP/1.1[0m" 500 -
2025-05-08 17:36:38,176 [INFO] 127.0.0.1 - - [08/May/2025 17:36:38] "GET /deadlines HTTP/1.1" 200 -
2025-05-08 17:36:38,192 [INFO] 127.0.0.1 - - [08/May/2025 17:36:38] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:36:39,627 [INFO] 127.0.0.1 - - [08/May/2025 17:36:39] "GET /shared_with_me HTTP/1.1" 200 -
2025-05-08 17:36:39,645 [INFO] 127.0.0.1 - - [08/May/2025 17:36:39] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:36:40,164 [INFO] 127.0.0.1 - - [08/May/2025 17:36:40] "GET /share HTTP/1.1" 200 -
2025-05-08 17:36:40,179 [INFO] 127.0.0.1 - - [08/May/2025 17:36:40] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:36:40,698 [INFO] 127.0.0.1 - - [08/May/2025 17:36:40] "GET /upload HTTP/1.1" 200 -
2025-05-08 17:36:40,710 [INFO] 127.0.0.1 - - [08/May/2025 17:36:40] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:36:41,333 [INFO] 127.0.0.1 - - [08/May/2025 17:36:41] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 17:36:41,350 [INFO] 127.0.0.1 - - [08/May/2025 17:36:41] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:36:42,339 [INFO] 127.0.0.1 - - [08/May/2025 17:36:42] "GET /upload HTTP/1.1" 200 -
2025-05-08 17:36:42,352 [INFO] 127.0.0.1 - - [08/May/2025 17:36:42] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:36:45,121 [ERROR] Exception on /grades [GET]
Traceback (most recent call last):
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 74, in wrapped_view
    return view(**kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 305, in grades_view
    return render_template('grades.html', grades=session.get('grades', []), courses=session.get('courses', []))
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/base.html", line 173, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 58, in block 'content'
    {% for unit, summary in summaries.items() %}
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 490, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'summaries' is undefined
2025-05-08 17:36:45,125 [INFO] 127.0.0.1 - - [08/May/2025 17:36:45] "[35m[1mGET /grades HTTP/1.1[0m" 500 -
2025-05-08 17:38:24,688 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-08 17:38:24,689 [INFO] [33mPress CTRL+C to quit[0m
2025-05-08 17:38:35,888 [INFO] 127.0.0.1 - - [08/May/2025 17:38:35] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-08 17:38:36,012 [INFO] 127.0.0.1 - - [08/May/2025 17:38:36] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 17:38:38,952 [INFO] 127.0.0.1 - - [08/May/2025 17:38:38] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:38:40,519 [ERROR] Exception on /grades [GET]
Traceback (most recent call last):
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 939, in finalize_request
    response = self.make_response(rv)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1212, in make_response
    raise TypeError(
TypeError: The view function for 'grades_view' did not return a valid response. The function either returned None or ended without a return statement.
2025-05-08 17:38:40,523 [INFO] 127.0.0.1 - - [08/May/2025 17:38:40] "[35m[1mGET /grades HTTP/1.1[0m" 500 -
2025-05-08 17:38:47,020 [INFO] 127.0.0.1 - - [08/May/2025 17:38:47] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-08 17:38:47,035 [INFO] 127.0.0.1 - - [08/May/2025 17:38:47] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 17:38:47,069 [INFO] 127.0.0.1 - - [08/May/2025 17:38:47] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:39:35,453 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-08 17:39:35,453 [INFO] [33mPress CTRL+C to quit[0m
2025-05-08 17:39:41,767 [INFO] 127.0.0.1 - - [08/May/2025 17:39:41] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-08 17:39:41,839 [INFO] 127.0.0.1 - - [08/May/2025 17:39:41] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 17:39:41,856 [INFO] 127.0.0.1 - - [08/May/2025 17:39:41] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:39:43,440 [ERROR] Exception on /grades [GET]
Traceback (most recent call last):
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 74, in wrapped_view
    return view(**kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 299, in grades_view
    return render_template(
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/base.html", line 173, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 75, in block 'content'
    const chartData = {{ chart_data|tojson }};
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/filters.py", line 1721, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/utils.py", line 669, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/json/provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/json/provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Undefined is not JSON serializable
2025-05-08 17:39:43,470 [INFO] 127.0.0.1 - - [08/May/2025 17:39:43] "[35m[1mGET /grades HTTP/1.1[0m" 500 -
2025-05-08 17:40:44,857 [INFO] 127.0.0.1 - - [08/May/2025 17:40:44] "GET /upload HTTP/1.1" 200 -
2025-05-08 17:40:44,877 [INFO] 127.0.0.1 - - [08/May/2025 17:40:44] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:40:46,825 [INFO] 127.0.0.1 - - [08/May/2025 17:40:46] "GET /deadlines HTTP/1.1" 200 -
2025-05-08 17:40:46,840 [INFO] 127.0.0.1 - - [08/May/2025 17:40:46] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:41:22,163 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-08 17:41:22,163 [INFO] [33mPress CTRL+C to quit[0m
2025-05-08 17:41:27,404 [INFO] 127.0.0.1 - - [08/May/2025 17:41:27] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-08 17:41:27,469 [INFO] 127.0.0.1 - - [08/May/2025 17:41:27] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 17:41:27,725 [INFO] 127.0.0.1 - - [08/May/2025 17:41:27] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:41:29,030 [ERROR] Exception on /grades [GET]
Traceback (most recent call last):
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 74, in wrapped_view
    return view(**kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 299, in grades_view
    return render_template(
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/base.html", line 173, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 75, in block 'content'
    const chartData = {{ chart_data|tojson }};
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/filters.py", line 1721, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/utils.py", line 669, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/json/provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/json/provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Undefined is not JSON serializable
2025-05-08 17:41:29,038 [INFO] 127.0.0.1 - - [08/May/2025 17:41:29] "[35m[1mGET /grades HTTP/1.1[0m" 500 -
2025-05-08 17:41:52,308 [INFO] 127.0.0.1 - - [08/May/2025 17:41:52] "GET /upload HTTP/1.1" 200 -
2025-05-08 17:41:52,336 [INFO] 127.0.0.1 - - [08/May/2025 17:41:52] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:41:59,932 [INFO] 127.0.0.1 - - [08/May/2025 17:41:59] "[32mPOST /add_course HTTP/1.1[0m" 302 -
2025-05-08 17:41:59,938 [INFO] 127.0.0.1 - - [08/May/2025 17:41:59] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 17:41:59,962 [INFO] 127.0.0.1 - - [08/May/2025 17:41:59] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:42:01,526 [INFO] 127.0.0.1 - - [08/May/2025 17:42:01] "GET /course/cits1111 HTTP/1.1" 200 -
2025-05-08 17:42:01,541 [INFO] 127.0.0.1 - - [08/May/2025 17:42:01] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:42:03,744 [INFO] 127.0.0.1 - - [08/May/2025 17:42:03] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 17:42:03,765 [INFO] 127.0.0.1 - - [08/May/2025 17:42:03] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:42:07,494 [ERROR] Exception on /grades [GET]
Traceback (most recent call last):
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 74, in wrapped_view
    return view(**kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 299, in grades_view
    return render_template(
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/base.html", line 173, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 75, in block 'content'
    const chartData = {{ chart_data|tojson }};
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/filters.py", line 1721, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/utils.py", line 669, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/json/provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/json/provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Undefined is not JSON serializable
2025-05-08 17:42:07,497 [INFO] 127.0.0.1 - - [08/May/2025 17:42:07] "[35m[1mGET /grades HTTP/1.1[0m" 500 -
2025-05-08 17:42:44,185 [INFO] 127.0.0.1 - - [08/May/2025 17:42:44] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 17:42:44,214 [INFO] 127.0.0.1 - - [08/May/2025 17:42:44] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:42:45,260 [ERROR] Exception on /grades [GET]
Traceback (most recent call last):
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 74, in wrapped_view
    return view(**kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 299, in grades_view
    return render_template(
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/base.html", line 173, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 75, in block 'content'
    const chartData = {{ chart_data|tojson }};
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/filters.py", line 1721, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/utils.py", line 669, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/json/provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/json/provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Undefined is not JSON serializable
2025-05-08 17:42:45,262 [INFO] 127.0.0.1 - - [08/May/2025 17:42:45] "[35m[1mGET /grades HTTP/1.1[0m" 500 -
2025-05-08 17:42:49,598 [INFO] 127.0.0.1 - - [08/May/2025 17:42:49] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-08 17:42:49,608 [INFO] 127.0.0.1 - - [08/May/2025 17:42:49] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 17:42:49,629 [INFO] 127.0.0.1 - - [08/May/2025 17:42:49] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:42:50,801 [ERROR] Exception on /grades [GET]
Traceback (most recent call last):
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 74, in wrapped_view
    return view(**kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 299, in grades_view
    return render_template(
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/base.html", line 173, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 75, in block 'content'
    const chartData = {{ chart_data|tojson }};
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/filters.py", line 1721, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/utils.py", line 669, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/json/provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/json/provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Undefined is not JSON serializable
2025-05-08 17:42:50,804 [INFO] 127.0.0.1 - - [08/May/2025 17:42:50] "[35m[1mGET /grades HTTP/1.1[0m" 500 -
2025-05-08 17:45:16,539 [INFO] 127.0.0.1 - - [08/May/2025 17:45:16] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 17:45:16,582 [INFO] 127.0.0.1 - - [08/May/2025 17:45:16] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:45:18,987 [ERROR] Exception on /grades [GET]
Traceback (most recent call last):
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 74, in wrapped_view
    return view(**kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 299, in grades_view
    return render_template(
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/base.html", line 173, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 75, in block 'content'
    <script>
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/filters.py", line 1721, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/utils.py", line 669, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/json/provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/json/provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Undefined is not JSON serializable
2025-05-08 17:45:18,991 [INFO] 127.0.0.1 - - [08/May/2025 17:45:18] "[35m[1mGET /grades HTTP/1.1[0m" 500 -
2025-05-08 17:45:24,481 [INFO] 127.0.0.1 - - [08/May/2025 17:45:24] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-08 17:45:24,497 [INFO] 127.0.0.1 - - [08/May/2025 17:45:24] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 17:45:24,571 [INFO] 127.0.0.1 - - [08/May/2025 17:45:24] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:45:25,851 [ERROR] Exception on /grades [GET]
Traceback (most recent call last):
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 74, in wrapped_view
    return view(**kwargs)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/app.py", line 299, in grades_view
    return render_template(
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/base.html", line 173, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/donnapeari/Desktop/agile-projec/StudyUdub-6/templates/grades.html", line 75, in block 'content'
    <script>
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/filters.py", line 1721, in do_tojson
    return htmlsafe_json_dumps(value, dumps=dumps, **kwargs)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/jinja2/utils.py", line 669, in htmlsafe_json_dumps
    dumps(obj, **kwargs)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/json/provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/donnapeari/Library/Python/3.9/lib/python/site-packages/flask/json/provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type Undefined is not JSON serializable
2025-05-08 17:45:25,853 [INFO] 127.0.0.1 - - [08/May/2025 17:45:25] "[35m[1mGET /grades HTTP/1.1[0m" 500 -
2025-05-08 17:45:36,304 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-08 17:45:36,305 [INFO] [33mPress CTRL+C to quit[0m
2025-05-08 17:45:40,833 [INFO] 127.0.0.1 - - [08/May/2025 17:45:40] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-08 17:45:40,915 [INFO] 127.0.0.1 - - [08/May/2025 17:45:40] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 17:45:40,930 [INFO] 127.0.0.1 - - [08/May/2025 17:45:40] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:45:42,078 [INFO] 127.0.0.1 - - [08/May/2025 17:45:42] "GET /grades HTTP/1.1" 200 -
2025-05-08 17:45:42,090 [INFO] 127.0.0.1 - - [08/May/2025 17:45:42] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:45:54,668 [INFO] 127.0.0.1 - - [08/May/2025 17:45:54] "[31m[1mPOST /grades HTTP/1.1[0m" 405 -
2025-05-08 17:46:08,914 [INFO] 127.0.0.1 - - [08/May/2025 17:46:08] "[31m[1mPOST /grades HTTP/1.1[0m" 405 -
2025-05-08 17:46:59,730 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-08 17:46:59,730 [INFO] [33mPress CTRL+C to quit[0m
2025-05-08 17:47:04,570 [INFO] 127.0.0.1 - - [08/May/2025 17:47:04] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-08 17:47:04,638 [INFO] 127.0.0.1 - - [08/May/2025 17:47:04] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 17:47:04,653 [INFO] 127.0.0.1 - - [08/May/2025 17:47:04] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:47:05,872 [INFO] 127.0.0.1 - - [08/May/2025 17:47:05] "GET /grades HTTP/1.1" 200 -
2025-05-08 17:47:05,888 [INFO] 127.0.0.1 - - [08/May/2025 17:47:05] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 17:47:13,758 [INFO] 127.0.0.1 - - [08/May/2025 17:47:13] "POST /grades HTTP/1.1" 200 -
2025-05-08 17:47:13,769 [INFO] 127.0.0.1 - - [08/May/2025 17:47:13] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 19:46:59,502 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-08 19:46:59,502 [INFO] [33mPress CTRL+C to quit[0m
2025-05-08 19:56:13,077 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-08 19:56:13,078 [INFO] [33mPress CTRL+C to quit[0m
2025-05-08 19:56:20,960 [ERROR] Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: Student

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_login\utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\werkzeug\local.py", line 318, in __get__
    obj = instance._get_current_object()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\werkzeug\local.py", line 526, in _get_current_object
    return get_name(local())
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_login\login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
  File "D:\Uni Local\CITS3403\StudyUdub\app.py", line 91, in load_user
    return Student.query.get(int(user_id))
  File "<string>", line 2, in get
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\util\deprecations.py", line 386, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\query.py", line 1126, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\query.py", line 1135, in _get_impl
    return self.session._get_impl(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 3874, in _get_impl
    return db_load_fn(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\loading.py", line 694, in load_on_pk_identity
    session.execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\context.py", line 306, in orm_execute_statement
    result = conn.execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: Student
[SQL: SELECT "Student"."StudentID" AS "Student_StudentID", "Student"."FirstName" AS "Student_FirstName", "Student"."LastName" AS "Student_LastName", "Student"."Email" AS "Student_Email", "Student"."Password" AS "Student_Password", "Student".totp_secret AS "Student_totp_secret", "Student"."Otp_Expiry" AS "Student_Otp_Expiry", "Student"."CreatedAt" AS "Student_CreatedAt" 
FROM "Student" 
WHERE "Student"."StudentID" = ?]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-08 19:56:21,044 [INFO] 127.0.0.1 - - [08/May/2025 19:56:21] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
2025-05-08 19:56:32,693 [INFO] 127.0.0.1 - - [08/May/2025 19:56:32] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-08 19:56:32,702 [ERROR] Exception on /dashboard [GET]
Traceback (most recent call last):
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: Student

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_login\utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\werkzeug\local.py", line 318, in __get__
    obj = instance._get_current_object()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\werkzeug\local.py", line 526, in _get_current_object
    return get_name(local())
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_login\login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
  File "D:\Uni Local\CITS3403\StudyUdub\app.py", line 91, in load_user
    return Student.query.get(int(user_id))
  File "<string>", line 2, in get
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\util\deprecations.py", line 386, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\query.py", line 1126, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\query.py", line 1135, in _get_impl
    return self.session._get_impl(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 3874, in _get_impl
    return db_load_fn(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\loading.py", line 694, in load_on_pk_identity
    session.execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\context.py", line 306, in orm_execute_statement
    result = conn.execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: Student
[SQL: SELECT "Student"."StudentID" AS "Student_StudentID", "Student"."FirstName" AS "Student_FirstName", "Student"."LastName" AS "Student_LastName", "Student"."Email" AS "Student_Email", "Student"."Password" AS "Student_Password", "Student".totp_secret AS "Student_totp_secret", "Student"."Otp_Expiry" AS "Student_Otp_Expiry", "Student"."CreatedAt" AS "Student_CreatedAt" 
FROM "Student" 
WHERE "Student"."StudentID" = ?]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-08 19:56:32,707 [INFO] 127.0.0.1 - - [08/May/2025 19:56:32] "[35m[1mGET /dashboard HTTP/1.1[0m" 500 -
2025-05-08 19:56:34,814 [ERROR] Exception on /dashboard [GET]
Traceback (most recent call last):
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: Student

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_login\utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\werkzeug\local.py", line 318, in __get__
    obj = instance._get_current_object()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\werkzeug\local.py", line 526, in _get_current_object
    return get_name(local())
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_login\login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
  File "D:\Uni Local\CITS3403\StudyUdub\app.py", line 91, in load_user
    return Student.query.get(int(user_id))
  File "<string>", line 2, in get
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\util\deprecations.py", line 386, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\query.py", line 1126, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\query.py", line 1135, in _get_impl
    return self.session._get_impl(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 3874, in _get_impl
    return db_load_fn(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\loading.py", line 694, in load_on_pk_identity
    session.execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\context.py", line 306, in orm_execute_statement
    result = conn.execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: Student
[SQL: SELECT "Student"."StudentID" AS "Student_StudentID", "Student"."FirstName" AS "Student_FirstName", "Student"."LastName" AS "Student_LastName", "Student"."Email" AS "Student_Email", "Student"."Password" AS "Student_Password", "Student".totp_secret AS "Student_totp_secret", "Student"."Otp_Expiry" AS "Student_Otp_Expiry", "Student"."CreatedAt" AS "Student_CreatedAt" 
FROM "Student" 
WHERE "Student"."StudentID" = ?]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-08 19:56:34,817 [INFO] 127.0.0.1 - - [08/May/2025 19:56:34] "[35m[1mGET /dashboard HTTP/1.1[0m" 500 -
2025-05-08 19:57:23,332 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-08 19:57:23,333 [INFO] [33mPress CTRL+C to quit[0m
2025-05-08 19:57:25,012 [ERROR] Exception on /dashboard [GET]
Traceback (most recent call last):
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: Student

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_login\utils.py", line 284, in decorated_view
    elif not current_user.is_authenticated:
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\werkzeug\local.py", line 318, in __get__
    obj = instance._get_current_object()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\werkzeug\local.py", line 526, in _get_current_object
    return get_name(local())
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_login\utils.py", line 25, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_login\utils.py", line 370, in _get_user
    current_app.login_manager._load_user()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_login\login_manager.py", line 364, in _load_user
    user = self._user_callback(user_id)
  File "D:\Uni Local\CITS3403\StudyUdub\app.py", line 90, in load_user
    return Student.query.get(int(user_id))
  File "<string>", line 2, in get
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\util\deprecations.py", line 386, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\query.py", line 1126, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\query.py", line 1135, in _get_impl
    return self.session._get_impl(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 3874, in _get_impl
    return db_load_fn(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\loading.py", line 694, in load_on_pk_identity
    session.execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 2365, in execute
    return self._execute_internal(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 2251, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\context.py", line 306, in orm_execute_statement
    result = conn.execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: Student
[SQL: SELECT "Student"."StudentID" AS "Student_StudentID", "Student"."FirstName" AS "Student_FirstName", "Student"."LastName" AS "Student_LastName", "Student"."Email" AS "Student_Email", "Student"."Password" AS "Student_Password", "Student".totp_secret AS "Student_totp_secret", "Student"."Otp_Expiry" AS "Student_Otp_Expiry", "Student"."CreatedAt" AS "Student_CreatedAt" 
FROM "Student" 
WHERE "Student"."StudentID" = ?]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-08 19:57:25,025 [INFO] 127.0.0.1 - - [08/May/2025 19:57:25] "[35m[1mGET /dashboard HTTP/1.1[0m" 500 -
2025-05-08 19:58:06,146 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-08 19:58:06,147 [INFO] [33mPress CTRL+C to quit[0m
2025-05-08 19:58:09,373 [INFO] 127.0.0.1 - - [08/May/2025 19:58:09] "[32mGET /dashboard HTTP/1.1[0m" 302 -
2025-05-08 19:58:09,430 [INFO] 127.0.0.1 - - [08/May/2025 19:58:09] "GET /login?next=/dashboard HTTP/1.1" 200 -
2025-05-08 19:58:09,587 [INFO] 127.0.0.1 - - [08/May/2025 19:58:09] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 19:58:11,281 [INFO] 127.0.0.1 - - [08/May/2025 19:58:11] "POST /login HTTP/1.1" 200 -
2025-05-08 19:58:11,311 [INFO] 127.0.0.1 - - [08/May/2025 19:58:11] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 19:58:13,367 [INFO] 127.0.0.1 - - [08/May/2025 19:58:13] "GET /signup HTTP/1.1" 200 -
2025-05-08 19:58:13,390 [INFO] 127.0.0.1 - - [08/May/2025 19:58:13] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 19:58:25,935 [INFO] 127.0.0.1 - - [08/May/2025 19:58:25] "[32mPOST /signup HTTP/1.1[0m" 302 -
2025-05-08 19:58:26,157 [INFO] 127.0.0.1 - - [08/May/2025 19:58:26] "GET /setup-2fa HTTP/1.1" 200 -
2025-05-08 19:58:26,184 [INFO] 127.0.0.1 - - [08/May/2025 19:58:26] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 19:58:35,171 [INFO] 127.0.0.1 - - [08/May/2025 19:58:35] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 19:58:35,189 [INFO] 127.0.0.1 - - [08/May/2025 19:58:35] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 19:58:39,459 [INFO] 127.0.0.1 - - [08/May/2025 19:58:39] "GET /upload HTTP/1.1" 200 -
2025-05-08 19:58:39,485 [INFO] 127.0.0.1 - - [08/May/2025 19:58:39] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 19:59:57,685 [ERROR] Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: CHECK constraint failed: notes_filepath_check

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\Uni Local\CITS3403\StudyUdub\app.py", line 99, in wrapped_view
    return view(**kwargs)
  File "D:\Uni Local\CITS3403\StudyUdub\app.py", line 313, in upload
    db.session.commit()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\scoping.py", line 599, in commit
    return self._proxied.commit()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 4353, in flush
    self._flush(objects)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 4488, in _flush
    with util.safe_reraise():
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 4449, in _flush
    flush_context.execute()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) CHECK constraint failed: notes_filepath_check
[SQL: INSERT INTO "Notes" ("StudentID", "CourseID", "Title", "Category", "Description", "FilePath", "CreatedAt") VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: (1, None, 'Hello', 'Lecture', '', '/secure_notes/fa731a078499129f9649deae406be4540fbaa50837ec1620b3c63a8e4e721ae8_CCGSCU_TRG_Officer_Manual.docx', '2025-05-08 11:59:57.684272')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-05-08 19:59:57,698 [INFO] 127.0.0.1 - - [08/May/2025 19:59:57] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
2025-05-08 20:03:36,320 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-08 20:03:36,321 [INFO] [33mPress CTRL+C to quit[0m
2025-05-08 20:03:40,330 [ERROR] Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: CHECK constraint failed: notes_filepath_check

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\Uni Local\CITS3403\StudyUdub\app.py", line 99, in wrapped_view
    return view(**kwargs)
  File "D:\Uni Local\CITS3403\StudyUdub\app.py", line 313, in upload
    db.session.commit()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\scoping.py", line 599, in commit
    return self._proxied.commit()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 4353, in flush
    self._flush(objects)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 4488, in _flush
    with util.safe_reraise():
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 4449, in _flush
    flush_context.execute()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) CHECK constraint failed: notes_filepath_check
[SQL: INSERT INTO "Notes" ("StudentID", "CourseID", "Title", "Category", "Description", "FilePath", "CreatedAt") VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: (1, None, 'Hello', 'Lecture', '', '/secure_notes/ffe24ec61dcbab43186b2e5d2e4c744dac60f638e653aafa55fe27d22b66e1d1_CCGSCU_TRG_Officer_Manual.docx', '2025-05-08 12:03:40.329239')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-05-08 20:03:40,343 [INFO] 127.0.0.1 - - [08/May/2025 20:03:40] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
2025-05-08 20:03:43,988 [INFO] 127.0.0.1 - - [08/May/2025 20:03:43] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-08 20:03:44,018 [INFO] 127.0.0.1 - - [08/May/2025 20:03:44] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 20:03:44,155 [INFO] 127.0.0.1 - - [08/May/2025 20:03:44] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 20:03:45,682 [INFO] 127.0.0.1 - - [08/May/2025 20:03:45] "GET /upload HTTP/1.1" 200 -
2025-05-08 20:03:45,705 [INFO] 127.0.0.1 - - [08/May/2025 20:03:45] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 20:04:01,120 [ERROR] Exception on /upload [POST]
Traceback (most recent call last):
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: CHECK constraint failed: notes_filepath_check

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "D:\Uni Local\CITS3403\StudyUdub\app.py", line 99, in wrapped_view
    return view(**kwargs)
  File "D:\Uni Local\CITS3403\StudyUdub\app.py", line 313, in upload
    db.session.commit()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\scoping.py", line 599, in commit
    return self._proxied.commit()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 2032, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 4353, in flush
    self._flush(objects)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 4488, in _flush
    with util.safe_reraise():
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\session.py", line 4449, in _flush
    flush_context.execute()
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1416, in execute
    return meth(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\sql\elements.py", line 523, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1843, in _execute_context
    return self._exec_single_context(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 2352, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\madtr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sqlalchemy\engine\default.py", line 945, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) CHECK constraint failed: notes_filepath_check
[SQL: INSERT INTO "Notes" ("StudentID", "CourseID", "Title", "Category", "Description", "FilePath", "CreatedAt") VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: (1, None, 'Hello', 'Lecture', '', '/secure_notes/216fed9a5dc04c816c45bf30b3b76a7d1bea517be3c321d759ec31549b741943_CCGSCU_TRG_Officer_Manual.docx', '2025-05-08 12:04:01.119873')]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2025-05-08 20:04:01,124 [INFO] 127.0.0.1 - - [08/May/2025 20:04:01] "[35m[1mPOST /upload HTTP/1.1[0m" 500 -
2025-05-08 20:16:18,583 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-08 20:16:18,588 [INFO] [33mPress CTRL+C to quit[0m
2025-05-08 20:16:27,673 [INFO] 127.0.0.1 - - [08/May/2025 20:16:27] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-08 20:16:27,724 [INFO] 127.0.0.1 - - [08/May/2025 20:16:27] "[32mGET /dashboard HTTP/1.1[0m" 302 -
2025-05-08 20:16:27,760 [INFO] 127.0.0.1 - - [08/May/2025 20:16:27] "GET /login?next=/dashboard HTTP/1.1" 200 -
2025-05-08 20:16:27,902 [INFO] 127.0.0.1 - - [08/May/2025 20:16:27] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 20:16:30,117 [INFO] 127.0.0.1 - - [08/May/2025 20:16:30] "POST /login HTTP/1.1" 200 -
2025-05-08 20:16:30,161 [INFO] 127.0.0.1 - - [08/May/2025 20:16:30] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 20:16:31,368 [INFO] 127.0.0.1 - - [08/May/2025 20:16:31] "GET /signup HTTP/1.1" 200 -
2025-05-08 20:16:31,388 [INFO] 127.0.0.1 - - [08/May/2025 20:16:31] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 20:16:56,383 [INFO] 127.0.0.1 - - [08/May/2025 20:16:56] "[32mPOST /signup HTTP/1.1[0m" 302 -
2025-05-08 20:16:56,447 [INFO] 127.0.0.1 - - [08/May/2025 20:16:56] "GET /setup-2fa HTTP/1.1" 200 -
2025-05-08 20:16:56,486 [INFO] 127.0.0.1 - - [08/May/2025 20:16:56] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 20:16:59,666 [INFO] 127.0.0.1 - - [08/May/2025 20:16:59] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 20:16:59,695 [INFO] 127.0.0.1 - - [08/May/2025 20:16:59] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 20:17:02,149 [INFO] 127.0.0.1 - - [08/May/2025 20:17:02] "GET /upload HTTP/1.1" 200 -
2025-05-08 20:17:02,184 [INFO] 127.0.0.1 - - [08/May/2025 20:17:02] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-08 20:17:16,788 [INFO] 127.0.0.1 - - [08/May/2025 20:17:16] "[32mPOST /upload HTTP/1.1[0m" 302 -
2025-05-08 20:17:16,794 [INFO] 127.0.0.1 - - [08/May/2025 20:17:16] "GET /dashboard HTTP/1.1" 200 -
2025-05-08 20:17:16,816 [INFO] 127.0.0.1 - - [08/May/2025 20:17:16] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 14:14:21,199 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-09 14:14:21,201 [INFO] [33mPress CTRL+C to quit[0m
2025-05-09 14:24:26,078 [INFO] 127.0.0.1 - - [09/May/2025 14:24:26] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-09 14:24:26,139 [INFO] 127.0.0.1 - - [09/May/2025 14:24:26] "[32mGET /dashboard HTTP/1.1[0m" 302 -
2025-05-09 14:24:26,256 [INFO] 127.0.0.1 - - [09/May/2025 14:24:26] "GET /login?next=/dashboard HTTP/1.1" 200 -
2025-05-09 14:24:26,473 [INFO] 127.0.0.1 - - [09/May/2025 14:24:26] "GET /static/uploads/StudyUdubLogo.png HTTP/1.1" 200 -
2025-05-09 14:24:26,844 [INFO] 127.0.0.1 - - [09/May/2025 14:24:26] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-05-09 14:24:34,782 [INFO] 127.0.0.1 - - [09/May/2025 14:24:34] "POST /login HTTP/1.1" 200 -
2025-05-09 14:24:34,823 [INFO] 127.0.0.1 - - [09/May/2025 14:24:34] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 14:25:28,713 [INFO] 127.0.0.1 - - [09/May/2025 14:25:28] "GET /signup HTTP/1.1" 200 -
2025-05-09 14:25:28,736 [INFO] 127.0.0.1 - - [09/May/2025 14:25:28] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 14:26:00,671 [INFO] 127.0.0.1 - - [09/May/2025 14:26:00] "[32mPOST /signup HTTP/1.1[0m" 302 -
2025-05-09 14:26:00,886 [INFO] 127.0.0.1 - - [09/May/2025 14:26:00] "GET /setup-2fa HTTP/1.1" 200 -
2025-05-09 14:26:00,915 [INFO] 127.0.0.1 - - [09/May/2025 14:26:00] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 14:26:12,296 [INFO] 127.0.0.1 - - [09/May/2025 14:26:12] "GET /dashboard HTTP/1.1" 200 -
2025-05-09 14:26:12,322 [INFO] 127.0.0.1 - - [09/May/2025 14:26:12] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 14:26:15,042 [INFO] 127.0.0.1 - - [09/May/2025 14:26:15] "GET /upload HTTP/1.1" 200 -
2025-05-09 14:26:15,070 [INFO] 127.0.0.1 - - [09/May/2025 14:26:15] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 14:27:22,934 [INFO] 127.0.0.1 - - [09/May/2025 14:27:22] "[32mPOST /upload HTTP/1.1[0m" 302 -
2025-05-09 14:27:22,940 [INFO] 127.0.0.1 - - [09/May/2025 14:27:22] "GET /dashboard HTTP/1.1" 200 -
2025-05-09 14:27:22,968 [INFO] 127.0.0.1 - - [09/May/2025 14:27:22] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 14:37:28,848 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-09 14:37:28,849 [INFO] [33mPress CTRL+C to quit[0m
2025-05-09 14:37:35,215 [INFO] 127.0.0.1 - - [09/May/2025 14:37:35] "[32mGET / HTTP/1.1[0m" 302 -
2025-05-09 14:37:35,252 [INFO] 127.0.0.1 - - [09/May/2025 14:37:35] "[32mGET /dashboard HTTP/1.1[0m" 302 -
2025-05-09 14:37:35,281 [INFO] 127.0.0.1 - - [09/May/2025 14:37:35] "GET /login?next=/dashboard HTTP/1.1" 200 -
2025-05-09 14:37:35,415 [INFO] 127.0.0.1 - - [09/May/2025 14:37:35] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 14:37:38,937 [INFO] 127.0.0.1 - - [09/May/2025 14:37:38] "GET /signup HTTP/1.1" 200 -
2025-05-09 14:37:38,959 [INFO] 127.0.0.1 - - [09/May/2025 14:37:38] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 14:38:37,857 [INFO] 127.0.0.1 - - [09/May/2025 14:38:37] "[32mPOST /signup HTTP/1.1[0m" 302 -
2025-05-09 14:38:37,914 [INFO] 127.0.0.1 - - [09/May/2025 14:38:37] "GET /setup-2fa HTTP/1.1" 200 -
2025-05-09 14:38:37,947 [INFO] 127.0.0.1 - - [09/May/2025 14:38:37] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 14:38:41,768 [INFO] 127.0.0.1 - - [09/May/2025 14:38:41] "GET /dashboard HTTP/1.1" 200 -
2025-05-09 14:38:41,791 [INFO] 127.0.0.1 - - [09/May/2025 14:38:41] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 15:12:07,810 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-09 15:12:07,811 [INFO] [33mPress CTRL+C to quit[0m
2025-05-09 15:12:13,938 [INFO] 127.0.0.1 - - [09/May/2025 15:12:13] "GET /dashboard HTTP/1.1" 200 -
2025-05-09 15:12:14,088 [INFO] 127.0.0.1 - - [09/May/2025 15:12:14] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 15:12:15,407 [INFO] 127.0.0.1 - - [09/May/2025 15:12:15] "GET /shared_with_me HTTP/1.1" 200 -
2025-05-09 15:12:15,436 [INFO] 127.0.0.1 - - [09/May/2025 15:12:15] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 15:12:16,238 [INFO] 127.0.0.1 - - [09/May/2025 15:12:16] "GET /share HTTP/1.1" 200 -
2025-05-09 15:12:16,266 [INFO] 127.0.0.1 - - [09/May/2025 15:12:16] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 15:13:42,501 [INFO] 127.0.0.1 - - [09/May/2025 15:13:42] "GET /upload HTTP/1.1" 200 -
2025-05-09 15:13:42,530 [INFO] 127.0.0.1 - - [09/May/2025 15:13:42] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 15:13:43,223 [INFO] 127.0.0.1 - - [09/May/2025 15:13:43] "GET /share HTTP/1.1" 200 -
2025-05-09 15:13:43,251 [INFO] 127.0.0.1 - - [09/May/2025 15:13:43] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 15:13:44,885 [INFO] 127.0.0.1 - - [09/May/2025 15:13:44] "GET /share HTTP/1.1" 200 -
2025-05-09 15:13:44,905 [INFO] 127.0.0.1 - - [09/May/2025 15:13:44] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 15:13:52,445 [INFO] [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2025-05-09 15:13:52,445 [INFO] [33mPress CTRL+C to quit[0m
2025-05-09 15:13:54,449 [INFO] 127.0.0.1 - - [09/May/2025 15:13:54] "GET /share HTTP/1.1" 200 -
2025-05-09 15:13:54,566 [INFO] 127.0.0.1 - - [09/May/2025 15:13:54] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 15:14:00,789 [INFO] 127.0.0.1 - - [09/May/2025 15:14:00] "GET /upload HTTP/1.1" 200 -
2025-05-09 15:14:00,816 [INFO] 127.0.0.1 - - [09/May/2025 15:14:00] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 15:14:14,609 [INFO] 127.0.0.1 - - [09/May/2025 15:14:14] "[32mPOST /upload HTTP/1.1[0m" 302 -
2025-05-09 15:14:14,624 [INFO] 127.0.0.1 - - [09/May/2025 15:14:14] "GET /dashboard HTTP/1.1" 200 -
2025-05-09 15:14:14,649 [INFO] 127.0.0.1 - - [09/May/2025 15:14:14] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 15:14:16,158 [INFO] 127.0.0.1 - - [09/May/2025 15:14:16] "GET /share HTTP/1.1" 200 -
2025-05-09 15:14:16,179 [INFO] 127.0.0.1 - - [09/May/2025 15:14:16] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 15:14:21,023 [INFO] 127.0.0.1 - - [09/May/2025 15:14:21] "GET /download/1 HTTP/1.1" 200 -
2025-05-09 15:15:27,462 [INFO] 127.0.0.1 - - [09/May/2025 15:15:27] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-05-09 15:15:45,941 [INFO] 127.0.0.1 - - [09/May/2025 15:15:45] "GET /upload HTTP/1.1" 200 -
2025-05-09 15:15:45,997 [INFO] 127.0.0.1 - - [09/May/2025 15:15:45] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 15:16:12,600 [INFO] 127.0.0.1 - - [09/May/2025 15:16:12] "[32mPOST /upload HTTP/1.1[0m" 302 -
2025-05-09 15:16:12,606 [INFO] 127.0.0.1 - - [09/May/2025 15:16:12] "GET /dashboard HTTP/1.1" 200 -
2025-05-09 15:16:12,628 [INFO] 127.0.0.1 - - [09/May/2025 15:16:12] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 15:16:19,561 [INFO] 127.0.0.1 - - [09/May/2025 15:16:19] "GET /share HTTP/1.1" 200 -
2025-05-09 15:16:19,585 [INFO] 127.0.0.1 - - [09/May/2025 15:16:19] "[36mGET /static/uploads/StudyUdubLogo.png HTTP/1.1[0m" 304 -
2025-05-09 15:16:24,439 [INFO] 127.0.0.1 - - [09/May/2025 15:16:24] "GET /download/2 HTTP/1.1" 200 -
2025-05-09 15:16:35,167 [INFO] 127.0.0.1 - - [09/May/2025 15:16:35] "[36mGET /download/1 HTTP/1.1[0m" 304 -
